WITH  PP_APP AS (
  SELECT 
    APHA.PREPAY_INVOICE_ID,
    APHA.PREPAY_LINE_NUM LINE_NUM,
	ROUND(SUM(APAD.AMOUNT), 2) TRX_AMOUNT
     -- SUM(NVL(AILA.BASE_AMOUNT, AILA.AMOUNT)) OPENING_BAL
  FROM AP_PREPAY_HISTORY_ALL APHA,
       AP_PREPAY_APP_DISTS APAD,
       XLA_EVENTS XE1
	   -- ap_invoice_lines_all aila
  WHERE APHA.PREPAY_HISTORY_ID = APAD.PREPAY_HISTORY_ID
    AND XE1.EVENT_ID = APHA.ACCOUNTING_EVENT_ID
    AND XE1.EVENT_STATUS_CODE = 'P'
    AND APAD.PREPAY_DIST_LOOKUP_CODE = 'PREPAY APPL'
	-- AND AILA.LINE_NUMBER=APHA.PREPAY_LINE_NUM
	-- AND AILA.INVOICE_ID=APHA.PREPAY_INVOICE_ID
    AND APHA.ACCOUNTING_DATE <= :p_from_accounting_date1
	-- AND TRUNC(APHA.ACCOUNTING_DATE) BETWEEN (:p_from_accounting_date1) 
                         -- AND (:p_to_accounting_date1)
  GROUP BY APHA.PREPAY_INVOICE_ID, APHA.PREPAY_LINE_NUM
)


 





	
SELECT

  SUM(NVL(AILA.BASE_AMOUNT, AILA.AMOUNT)) OPENING_BALANCE_AVD,
  PS.VENDOR_NAME
  -- OPEN_BAL.OPENING_BAL+NVL(AILA.BASE_AMOUNT, AILA.AMOUNT) CLOSING BALANCE
 -- NVL(AILA.BASE_AMOUNT, AILA.AMOUNT) + NVL(PP_APP.PP_ACC_AMOUNT, 0) AS ACCOUNTED_REMAINING_BALANCE
FROM AP_INVOICES_ALL AIA
JOIN HR_OPERATING_UNITS HRO ON AIA.ORG_ID = HRO.ORGANIZATION_ID
JOIN POZ_SUPPLIERS_V PS ON AIA.VENDOR_ID = PS.VENDOR_ID
JOIN POZ_SUPPLIER_SITES_ALL_M PSS ON AIA.VENDOR_ID = PSS.VENDOR_ID AND AIA.VENDOR_SITE_ID = PSS.VENDOR_SITE_ID
JOIN AP_INVOICE_LINES_ALL AILA ON AIA.INVOICE_ID = AILA.INVOICE_ID
JOIN AP_INVOICE_DISTRIBUTIONS_ALL AIDA ON AIDA.INVOICE_ID = AILA.INVOICE_ID AND AIDA.INVOICE_LINE_NUMBER = AILA.LINE_NUMBER
JOIN GL_CODE_COMBINATIONS GCC ON AIDA.DIST_CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
LEFT JOIN PP_APP ON PP_APP.PREPAY_INVOICE_ID = AIA.INVOICE_ID AND PP_APP.LINE_NUM = AILA.LINE_NUMBER
-- LEFT JOIN open_bal ON open_bal.PREPAY_INVOICE_ID = AIA.INVOICE_ID AND open_bal.LINE_NUM = AILA.LINE_NUMBER
JOIN GL_LEDGERS GL ON GL.LEDGER_ID = AIDA.SET_OF_BOOKS_ID
JOIN XLA_EVENTS XE ON XE.EVENT_ID = AIDA.ACCOUNTING_EVENT_ID
JOIN fnd_lookup_values flv ON flv.LOOKUP_CODE=PS.VENDOR_TYPE_LOOKUP_CODE 
WHERE AIA.INVOICE_TYPE_LOOKUP_CODE = 'PREPAYMENT'
  AND AIDA.LINE_TYPE_LOOKUP_CODE = 'ITEM'
  AND XE.EVENT_STATUS_CODE = 'P'
  AND UPPER(flv.LOOKUP_TYPE) ='POZ_VENDOR_TYPE'
AND flv.SOURCE_LANG='US'
AND flv.LOOKUP_CODE=PS.VENDOR_TYPE_LOOKUP_CODE  
  AND (AILA.AMOUNT + NVL(PP_APP.TRX_AMOUNT, 0)) <> 0.00
  -- AND AIDA.ACCOUNTING_DATE < :P_ACCOUNTING_DATE + 1
     -- AND TRUNC(AIA.GL_DATE) BETWEEN (:p_from_accounting_date1) 
                         -- AND (:p_to_accounting_date1)
				AND TRUNC(AIA.GL_DATE)		 <= :p_from_accounting_date1
  and (GL.NAME IN (:p_Ledger1) OR 'All' IN (:p_Ledger1 || 'All'))
    and (PS.VENDOR_NAME IN (:p_Supplier_Name) OR 'All' IN (:p_Supplier_Name || 'All'))
	  and (HRO.NAME IN (:p_Business_Unit) OR 'All' IN (:p_Business_Unit || 'All'))
	  -- and  (flv.meaning IN (:P_VENDOR_TYPE) OR 'All' IN (:P_VENDOR_TYPE || 'All'))
	  GROUP BY PS.VENDOR_NAME